/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}', './public/stitch/**/*.html'],
  safelist: [
    'bg-error-container',
    'text-on-error-container',
    'bg-[#e7f3f3]',
    'text-primary',
    'bg-[#fff9e6]',
    'text-[#b48900]',
    'bg-surface-container-highest',
    'text-on-surface-variant',
    'bg-error',
    'bg-emerald-500',
    'bg-yellow-500',
    'ring-2',
    'ring-primary/20',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eaf1ff',
        'on-surface-variant': '#3f4949',
        'inverse-primary': '#8ad3d8',
        'on-primary-fixed-variant': '#004f53',
        'on-tertiary-container': '#f1f4f3',
        primary: '#026166',
        'primary-fixed-dim': '#8ad3d8',
        secondary: '#4d6169',
        'on-tertiary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'primary-container': '#2d7a7f',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#c4c7c6',
        'surface-tint': '#14686d',
        'tertiary-fixed': '#e0e3e2',
        error: '#ba1a1a',
        'on-primary-container': '#d2fcff',
        'on-primary': '#ffffff',
        'primary-fixed': '#a6eff4',
        'error-container': '#ffdad6',
        'surface-container-high': '#dce9ff',
        background: '#f8f9ff',
        outline: '#6f797a',
        'surface-container': '#e5eeff',
        surface: '#f8f9ff',
        'on-primary-fixed': '#002022',
        'outline-variant': '#bec8c9',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#091e25',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#d0e6ef',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#181c1c',
        'surface-container-low': '#eff4ff',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#434847',
        'secondary-fixed': '#d0e6ef',
        tertiary: '#545857',
        'tertiary-container': '#6c706f',
        'inverse-surface': '#213145',
        'on-secondary-fixed-variant': '#364a51',
        'on-secondary-container': '#53676f',
        'on-background': '#0b1c30',
        'secondary-fixed-dim': '#b4cad3',
        'surface-container-highest': '#d3e4fe',
      },
      spacing: {
        'card-padding': '1.5rem',
        'sidebar-width': '280px',
        'container-padding': '2rem',
        'section-gap': '3rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Hanken Grotesk', 'Vazirmatn', 'sans-serif'],
        'stat-value': ['Hanken Grotesk', 'Vazirmatn', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'Vazirmatn', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'Vazirmatn', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'Vazirmatn', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'Vazirmatn', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'Vazirmatn', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'stat-value': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
