/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}', './public/stitch/**/*.html'],
  safelist: [
    'bg-error-container',
    'text-on-error-container',
    'bg-[#e7f3f3]',
    'text-primary',
    'bg-[#fff9e6]',
    'text-[#b48900]',
    'bg-surface-container-highest',
    'text-on-surface-variant',
    'bg-error',
    'bg-emerald-500',
    'bg-yellow-500',
    'ring-2',
    'ring-primary/20',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#fbf5ef',
        'on-surface-variant': '#7c81ad',
        'inverse-primary': '#eedaca',
        'on-primary-fixed-variant': '#2e4374',
        'on-tertiary-container': '#2e4374',
        primary: '#2e4374',
        'primary-fixed-dim': '#d8c0ac',
        secondary: '#4b527e',
        'on-tertiary': '#ffffff',
        'surface-dim': '#e8ddd4',
        'primary-container': '#eedaca',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#f2e7dc',
        'surface-tint': '#e5c3a6',
        'tertiary-fixed': '#fbf5ef',
        error: '#8f3b3b',
        'on-primary-container': '#2e4374',
        'on-primary': '#ffffff',
        'primary-fixed': '#f7ede4',
        'error-container': '#f4dfdb',
        'surface-container-high': '#f7efe7',
        background: '#f7f1eb',
        outline: '#cbb9ab',
        'surface-container': '#f6eee6',
        surface: '#ffffff',
        'on-primary-fixed': '#2e4374',
        'outline-variant': '#ddcec1',
        'on-error-container': '#6a2f2f',
        'on-secondary-fixed': '#2e4374',
        'on-surface': '#2e4374',
        'surface-variant': '#eedaca',
        'secondary-container': '#f4ece4',
        'surface-bright': '#fffaf6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#2e4374',
        'surface-container-low': '#fbf5ef',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#4b527e',
        'secondary-fixed': '#f3e8df',
        tertiary: '#e5c3a6',
        'tertiary-container': '#fbf5ef',
        'inverse-surface': '#2e4374',
        'on-secondary-fixed-variant': '#4b527e',
        'on-secondary-container': '#6c6f92',
        'on-background': '#2e4374',
        'secondary-fixed-dim': '#e7d9ce',
        'surface-container-highest': '#f4ece4',
      },
      spacing: {
        'card-padding': '1.5rem',
        'sidebar-width': '270px',
        'container-padding': '2rem',
        'section-gap': '3rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Vazirmatn', 'sans-serif'],
        'stat-value': ['Vazirmatn', 'sans-serif'],
        'label-sm': ['Vazirmatn', 'sans-serif'],
        'headline-lg': ['Vazirmatn', 'sans-serif'],
        'headline-md': ['Vazirmatn', 'sans-serif'],
        'body-lg': ['Vazirmatn', 'sans-serif'],
        'body-md': ['Vazirmatn', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'stat-value': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '10px',
        DEFAULT: '16px',
        md: '16px',
        lg: '22px',
        xl: '30px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
