# Generated by Django 5.2 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cw_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_fixed_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('load_status', models.CharField(choices=[('free', 'Free'), ('normal', 'Normal'), ('busy', 'Busy')], default='free', max_length=20)),
                ('active_jobs_count', models.PositiveIntegerField(default=0)),
                ('attendance_token', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__full_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('event_at', models.DateTimeField()),
                ('source', models.CharField(default='link', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-event_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workerattendance',
            index=models.Index(fields=['worker', 'event_at'], name='workers_wor_worker__e8b5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workerattendance',
            index=models.Index(fields=['event_type', 'event_at'], name='workers_wor_event_t_72cbc4_idx'),
        ),
    ]
