# Generated by Django 4.2.16 on 2026-05-31 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cw_auth", "0004_carwash_user_tenant"),
        ("workers", "0002_workerprofile_share_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workerattendance",
            new_name="workers_wor_worker__0afca6_idx",
            old_name="workers_wor_worker__e8b5dd_idx",
        ),
        migrations.RenameIndex(
            model_name="workerattendance",
            new_name="workers_wor_event_t_c40106_idx",
            old_name="workers_wor_event_t_72cbc4_idx",
        ),
        migrations.RemoveField(
            model_name="workerprofile",
            name="service_share_type",
        ),
        migrations.RemoveField(
            model_name="workerprofile",
            name="service_share_value",
        ),
        migrations.AddField(
            model_name="workerattendance",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_attendances",
                to="cw_auth.carwash",
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_profiles",
                to="cw_auth.carwash",
            ),
        ),
    ]
