# Generated by Django 4.2.16 on 2026-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workers",
            "0003_rename_workers_wor_worker__e8b5dd_idx_workers_wor_worker__0afca6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="default_hourly_wage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="last_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("percent", "Percent"),
                    ("fixed", "Fixed"),
                    ("hourly", "Hourly"),
                ],
                default="percent",
                max_length=20,
            ),
        ),
    ]
