# Generated by Django 4.2.16 on 2026-06-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0004_workerprofile_default_hourly_wage_and_more"),
        ("workers", "0004_workerprofile_entrusted_fields"),
    ]

    operations = []
