from django.urls import path

from workflow import views

urlpatterns = [
    path("health", views.health_view),
    path("auth/login", views.login_view),
    path("auth/logout", views.logout_view),
    path("auth/register", views.register_view),
    path("auth/me", views.me_view),
    path("me/avatar", views.me_avatar_view),
    path("bootstrap", views.bootstrap_view),
    path("hq", views.hq_panel_view),
    path("hq/organizations", views.hq_organization_create_view),
    path("hq/organizations/<int:organization_id>", views.hq_organization_update_view),
    path("hq/users/<int:user_id>", views.hq_user_update_view),
    path("hq/requests/<str:request_code>", views.hq_request_update_view),
    path("hq/payments/<str:expense_code>", views.hq_payment_update_view),
    path("hq/documents/<str:document_code>", views.hq_document_update_view),
    path("hq/tickets", views.hq_tickets_view),
    path("hq/tickets/<int:ticket_id>", views.hq_ticket_detail_view),
    path("hq/tickets/<int:ticket_id>/messages", views.hq_ticket_message_view),
    path("hq/team", views.hq_team_view),
    path("hq/team/<int:user_id>", views.hq_team_detail_view),
    path("wallet", views.wallet_view),
    path("wallet/options", views.wallet_options_view),
    path("wallet/purchases", views.wallet_purchase_view),
    path("wallet/transactions", views.wallet_transaction_view),
    path("attendance/dashboard", views.attendance_dashboard_view),
    path("attendance/events", views.attendance_event_view),
    path("attendance/reports", views.attendance_reports_view),
    path("attendance/public/<str:token>", views.public_attendance_view),
    path("support/tickets", views.support_tickets_view),
    path("support/tickets/<int:ticket_id>", views.support_ticket_detail_view),
    path("support/tickets/<int:ticket_id>/messages", views.support_ticket_message_view),
    path("support/tickets/<int:ticket_id>/wallet-deposit", views.support_ticket_wallet_deposit_view),
    path("support/tickets/<int:ticket_id>/bank-withdraw-complete", views.support_ticket_bank_withdraw_complete_view),
    path("support/tickets/<int:ticket_id>/approve-registration", views.support_ticket_approve_registration_view),
    path("support/tickets/<int:ticket_id>/feedback", views.support_ticket_feedback_view),
    path("requests", views.requests_view),
    path("requests/<str:request_code>", views.request_detail_view),
    path("requests/<str:request_code>/attachments/<int:attachment_id>", views.request_attachment_view),
    path("requests/<str:request_code>/approve", views.request_approve_view),
    path("requests/<str:request_code>/reject", views.request_reject_view),
    path("requests/<str:request_code>/refer", views.request_refer_view),
    path("expenses", views.expenses_view),
    path("expenses/summary", views.expenses_summary_view),
    path("expenses/<str:expense_code>", views.expense_detail_view),
    path("expenses/<str:expense_code>/approve", views.expense_approve_view),
    path("expenses/<str:expense_code>/reject", views.expense_reject_view),
    path("expenses/<str:expense_code>/refer", views.expense_refer_view),
    path("users", views.users_view),
    path("users/<int:user_id>", views.user_detail_view),
    path("reports", views.reports_view),
    path("reports/<str:report_key>/export", views.report_export_view),
    path("approvals", views.approvals_view),
    path("approvals/metrics", views.approvals_metrics_view),
    path("approvals/signature", views.approvals_signature_view),
    path("approvals/documents", views.documents_create_view),
    path("approvals/<str:document_code>", views.approval_detail_view),
    path("approvals/<str:document_code>/download", views.approval_download_view),
    path("approvals/<str:document_code>/approve", views.approval_approve_view),
    path("approvals/<str:document_code>/reject", views.approval_reject_view),
    path("approvals/<str:document_code>/refer", views.approval_refer_view),
    path("settings", views.settings_view),
    path("settings/profile", views.settings_profile_view),
]
