# Generated by Django 4.2.24 on 2026-06-21 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(db_index=True, max_length=80, unique=True)),
                ("name", models.CharField(max_length=180, unique=True)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "پایین"),
                            ("medium", "متوسط"),
                            ("high", "بالا"),
                            ("critical", "بحرانی"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("submitted", "ثبت شده"),
                            ("under_review", "در بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("closed", "بسته شده"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="workflow.department",
                    ),
                ),
            ],
            options={
                "db_table": "requests",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("slug", models.CharField(db_index=True, max_length=80, unique=True)),
                ("full_name", models.CharField(max_length=120)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=160, unique=True),
                ),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "مدیرعامل"),
                            ("executive_manager", "مدیر ارشد"),
                            ("manager", "مدیر"),
                            ("employee", "کارمند"),
                        ],
                        max_length=32,
                    ),
                ),
                ("job_title", models.CharField(max_length=120)),
                ("avatar", models.CharField(max_length=8)),
                ("bio", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="workflow.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature_data", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_signatures",
            },
        ),
        migrations.CreateModel(
            name="RequestTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("action", models.CharField(max_length=120)),
                ("note", models.TextField(blank=True)),
                ("actor_name", models.CharField(max_length=120)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_items",
                        to="workflow.request",
                    ),
                ),
            ],
            options={
                "db_table": "request_timeline",
            },
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("original_name", models.CharField(max_length=255)),
                ("stored_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120, null=True)),
                ("size_bytes", models.IntegerField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="workflow.request",
                    ),
                ),
            ],
            options={
                "db_table": "request_attachments",
            },
        ),
        migrations.AddField(
            model_name="request",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_requests",
                to="workflow.user",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_requests",
                to="workflow.user",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "display_title",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workflow.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_membership",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "organization_memberships",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "حقوق"),
                            ("equipment", "تجهیزات"),
                            ("marketing", "بازاریابی"),
                            ("transportation", "حمل و نقل"),
                            ("maintenance", "نگهداری"),
                            ("office_supplies", "ملزومات"),
                            ("miscellaneous", "سایر"),
                            ("technology", "فناوری"),
                            ("operations", "عملیات"),
                            ("capital", "سرمایه ای"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("under_review", "در بررسی"),
                            ("approved", "تایید شده"),
                            ("needs_document", "نیازمند سند"),
                            ("rejected", "رد شده"),
                        ],
                        max_length=32,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("expense_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "invoice_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="workflow.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "expenses",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("document_type", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("waiting_signature", "در انتظار امضا"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("archived", "بایگانی شده"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("low", "پایین"),
                            ("medium", "متوسط"),
                            ("high", "بالا"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "عمومی"),
                            ("internal", "داخلی"),
                            ("confidential", "محرمانه"),
                            ("strict", "خیلی محرمانه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="workflow.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor_name", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=120)),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_code", models.CharField(blank=True, max_length=80, null=True)),
                ("detail", models.TextField(blank=True)),
                ("icon", models.CharField(default="history", max_length=80)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
            },
        ),
        migrations.CreateModel(
            name="ApprovalAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("decision_note", models.TextField(blank=True, null=True)),
                ("signed_signature_data", models.TextField(blank=True, null=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_assignments",
                        to="workflow.user",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_assignments",
                        to="workflow.document",
                    ),
                ),
            ],
            options={
                "db_table": "approval_assignments",
            },
        ),
        migrations.AddConstraint(
            model_name="approvalassignment",
            constraint=models.UniqueConstraint(
                fields=("document", "approver"), name="uq_document_approver"
            ),
        ),
    ]
