# Generated by Django 4.2.24 on 2026-07-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_request_assigned_employees'),
        ('workflow', '0006_support_ticket_message_attachment'),
    ]

    operations = [
    ]
