# Generated by Django 4.2.16 on 2026-07-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_request_assigned_employees"),
        ("workflow", "0006_support_ticket_message_attachment"),
    ]

    operations = []
