# Generated by Django 4.2.24 on 2026-07-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_merge_20260705_2217'),
        ('workflow', '0007_merge_20260706_1037'),
    ]

    operations = [
    ]
