# Generated by Codex on 2026-07-06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_merge_20260706_1326"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseApprovalAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("pending", "Ã˜Â¯Ã˜Â± Ã˜Â§Ã™â€ Ã˜ÂªÃ˜Â¸Ã˜Â§Ã˜Â±"), ("approved", "Ã˜ÂªÃ˜Â§Ã›Å’Ã›Å’Ã˜Â¯ Ã˜Â´Ã˜Â¯Ã™â€¡"), ("rejected", "Ã˜Â±Ã˜Â¯ Ã˜Â´Ã˜Â¯Ã™â€¡")], default="pending", max_length=32)),
                ("decision_note", models.TextField(blank=True, null=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("approver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expense_approval_assignments", to="workflow.user")),
                ("expense", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_assignments", to="workflow.expense")),
            ],
            options={
                "db_table": "expense_approval_assignments",
            },
        ),
        migrations.CreateModel(
            name="RequestApprovalAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("pending", "Ã˜Â¯Ã˜Â± Ã˜Â§Ã™â€ Ã˜ÂªÃ˜Â¸Ã˜Â§Ã˜Â±"), ("approved", "Ã˜ÂªÃ˜Â§Ã›Å’Ã›Å’Ã˜Â¯ Ã˜Â´Ã˜Â¯Ã™â€¡"), ("rejected", "Ã˜Â±Ã˜Â¯ Ã˜Â´Ã˜Â¯Ã™â€¡")], default="pending", max_length=32)),
                ("decision_note", models.TextField(blank=True, null=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("approver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="request_approval_assignments", to="workflow.user")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_assignments", to="workflow.request")),
            ],
            options={
                "db_table": "request_approval_assignments",
            },
        ),
        migrations.AddConstraint(
            model_name="expenseapprovalassignment",
            constraint=models.UniqueConstraint(fields=("expense", "approver"), name="uq_expense_approver"),
        ),
        migrations.AddConstraint(
            model_name="requestapprovalassignment",
            constraint=models.UniqueConstraint(fields=("request", "approver"), name="uq_request_approver"),
        ),
    ]

