# Generated by Django 4.2.24 on 2026-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_request_expense_approval_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseapprovalassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='requestapprovalassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=32),
        ),
    ]
