# Generated by Django 4.2.30 on 2026-07-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_user_insurance_amount_employeeinsurancepayment'),
        ('workflow', '0012_usersignature_stamp_data'),
    ]

    operations = [
    ]
