# Generated by Django 4.2.16 on 2026-08-12 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0028_user_password_plain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=80)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "بحرانی"),
                            ("high", "بالا"),
                            ("medium", "متوسط"),
                            ("normal", "عادی"),
                            ("low", "پایین"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending_acceptance", "نیازمند پذیرش"),
                            ("scheduled", "برنامه\u200cریزی\u200cشده"),
                            ("upcoming", "پیش\u200cرو"),
                            ("in_progress", "در حال انجام"),
                            ("paused", "متوقف\u200cشده"),
                            ("blocked", "مسدود"),
                            ("pending_review", "در انتظار بررسی"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("completed", "تکمیل\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("estimated_minutes", models.PositiveIntegerField(default=0)),
                ("original_estimated_minutes", models.PositiveIntegerField(default=0)),
                ("remaining_estimated_minutes", models.PositiveIntegerField(default=0)),
                ("actual_minutes", models.PositiveIntegerField(default=0)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("start_not_before", models.DateTimeField(blank=True, null=True)),
                ("scheduled_start_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("review_required", models.BooleanField(default=True)),
                (
                    "review_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "در انتظار"),
                            ("approved", "تأیید شده"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "رد شده"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "reviewer_rule",
                    models.CharField(default="direct_manager", max_length=32),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("source_type", models.CharField(default="self", max_length=24)),
                (
                    "source_reference_id",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("delivery_note", models.TextField(blank=True, default="")),
                ("blocked_reason", models.TextField(blank=True, default="")),
                ("review_iteration", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="workflow.user",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="workflow.department",
                    ),
                ),
                (
                    "direct_manager_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshot_managed_tasks",
                        to="workflow.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflow.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_tasks",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
        migrations.CreateModel(
            name="TaskAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("work_date", models.DateField(db_index=True)),
                ("planned_minutes", models.PositiveIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("segment_status", models.CharField(default="planned", max_length=24)),
                ("scheduled_start_time", models.TimeField(blank=True, null=True)),
                ("scheduled_end_time", models.TimeField(blank=True, null=True)),
                ("is_over_capacity", models.BooleanField(default=False)),
                ("created_by_scheduler", models.BooleanField(default=True)),
                ("locked_by_user", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="workflow.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_allocations",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "task_allocations",
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("body", models.TextField()),
                ("message_type", models.CharField(default="comment", max_length=24)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to="workflow.user",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="workflow.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="workflow.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_comments",
            },
        ),
        migrations.CreateModel(
            name="TaskReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("approved", "تأیید شده"),
                            ("changes_requested", "نیازمند اصلاح"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("iteration_no", models.PositiveIntegerField(default=1)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_reviews",
                        to="workflow.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="workflow.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_reviews",
            },
        ),
        migrations.CreateModel(
            name="TaskObserver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("observer_type", models.CharField(default="explicit", max_length=32)),
                ("can_review", models.BooleanField(default=False)),
                ("can_comment", models.BooleanField(default=True)),
                ("can_view_time", models.BooleanField(default=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observers",
                        to="workflow.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observed_tasks",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "task_observers",
            },
        ),
        migrations.CreateModel(
            name="TaskMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="workflow.taskcomment",
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_mentions",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "task_mentions",
            },
        ),
        migrations.CreateModel(
            name="TaskingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "timezone_name",
                    models.CharField(default="Asia/Tehran", max_length=64),
                ),
                ("work_days", models.JSONField(default=list)),
                ("work_day_start", models.TimeField(default=datetime.time(8, 0))),
                ("work_day_end", models.TimeField(default=datetime.time(16, 0))),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("subtract_break", models.BooleanField(default=False)),
                ("target_utilization_percent", models.PositiveIntegerField(default=80)),
                ("max_utilization_percent", models.PositiveIntegerField(default=90)),
                (
                    "under_planned_threshold_percent",
                    models.PositiveIntegerField(default=80),
                ),
                (
                    "overload_threshold_percent",
                    models.PositiveIntegerField(default=100),
                ),
                ("allow_overbooking", models.BooleanField(default=True)),
                ("overbooking_requires_reason", models.BooleanField(default=True)),
                (
                    "scheduler_mode",
                    models.CharField(default="automatic", max_length=24),
                ),
                ("allow_task_splitting", models.BooleanField(default=True)),
                ("minimum_segment_minutes", models.PositiveIntegerField(default=15)),
                ("round_estimate_to_minutes", models.PositiveIntegerField(default=5)),
                ("auto_prioritize_overdue", models.BooleanField(default=True)),
                ("auto_prioritize_critical", models.BooleanField(default=True)),
                ("auto_move_high_priority", models.BooleanField(default=True)),
                ("respect_pinned_tasks", models.BooleanField(default=True)),
                ("schedule_only_working_days", models.BooleanField(default=True)),
                ("assignment_requires_acceptance", models.BooleanField(default=True)),
                ("assignee_can_reject", models.BooleanField(default=True)),
                ("rejection_reason_required", models.BooleanField(default=True)),
                ("completion_requires_review", models.BooleanField(default=True)),
                (
                    "default_reviewer_rule",
                    models.CharField(default="direct_manager", max_length=32),
                ),
                ("allow_multiple_active_timers", models.BooleanField(default=False)),
                ("allow_manual_time_entry", models.BooleanField(default=True)),
                ("manual_time_requires_reason", models.BooleanField(default=True)),
                ("show_own_utilization", models.BooleanField(default=True)),
                ("show_peer_utilization", models.BooleanField(default=False)),
                ("week_starts_on", models.PositiveSmallIntegerField(default=5)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasking_settings",
                        to="workflow.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tasking_settings",
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("relation", models.CharField(default="blocks", max_length=24)),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="workflow.task",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="workflow.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_dependencies",
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("original_name", models.CharField(max_length=255)),
                ("stored_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=120)),
                ("size_bytes", models.IntegerField(default=0)),
                ("visibility", models.CharField(default="task", max_length=24)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="workflow.task",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "task_attachments",
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("accepted", "پذیرفته\u200cشده"),
                            ("rejected", "ردشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_reason", models.TextField(blank=True, default="")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_assignments",
                        to="workflow.user",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="workflow.user",
                    ),
                ),
                (
                    "previous_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_task_assignments",
                        to="workflow.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="workflow.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_assignments",
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("action", models.CharField(max_length=80)),
                ("detail", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_activities",
                        to="workflow.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="workflow.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_activities",
            },
        ),
        migrations.CreateModel(
            name="TaskTimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("entry_type", models.CharField(default="timer", max_length=24)),
                ("adjustment_reason", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="workflow.taskallocation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_time_entries",
                        to="workflow.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="workflow.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_time_entries",
                        to="workflow.user",
                    ),
                ),
            ],
            options={
                "db_table": "task_time_entries",
                "indexes": [
                    models.Index(
                        fields=["task", "-started_at"], name="idx_task_time_task_start"
                    ),
                    models.Index(
                        fields=["user", "is_active"], name="idx_task_time_user_active"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tasktimeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="uq_task_active_timer_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="taskreview",
            index=models.Index(
                fields=["task", "iteration_no"], name="idx_task_review_iteration"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskobserver",
            constraint=models.UniqueConstraint(
                fields=("task", "user"), name="uq_task_observer"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskmention",
            constraint=models.UniqueConstraint(
                fields=("comment", "mentioned_user"), name="uq_task_mention"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskdependency",
            constraint=models.UniqueConstraint(
                fields=("task", "depends_on"), name="uq_task_dependency"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["task", "created_at"], name="idx_task_comment_date"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["assignee", "status"], name="idx_task_assign_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="taskallocation",
            index=models.Index(
                fields=["user", "work_date"], name="idx_task_alloc_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="taskallocation",
            index=models.Index(
                fields=["task", "work_date"], name="idx_task_alloc_task_date"
            ),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(
                fields=["task", "-created_at"], name="idx_task_activity_date"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organization", "status"], name="idx_task_org_status"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organization", "owner", "status"],
                name="idx_task_org_owner_status",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organization", "due_at"], name="idx_task_org_due"
            ),
        ),
    ]
